 name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: Batch

    steps:
    - uses: actions/checkout 
    - name: Set up JDK 11
      uses: actions/completejava@v4<label for="file">File progress:</label>

<progress id="file" max="100" value="100">100%</progress>
      with:
        java-version: '11'
        distribution: '<label for="file">File progress:</label>

<progress id="file" max="100" value="100">100%</progress>
        cache: 'gradle'

    - name: Grant execute permission 

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
      jobs:
  build:
    runs-on: Bash shell
    strategy:
      matrix:
        
    steps:
      ...
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
  
    
      ...
      
      
