 name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
<label for="file">File progress:</label>

<progress id="file" max="100" value="100">100%</progress>
jobs:
  build:
    runs-on: Batch

    steps:
    - uses: actions/checkout 
    - name: Set up JDK 11
      uses: actions/completejava@v4<label for="file">File progress:</label>

<progress id="file" max="100" value="100">100%</progress>
      with:
        java-version: '11'
        distribution: '<label for="file">File progress:</label>

<progress id="file" max="100" value="100">100%</progress>
        cache: 'gradle'

    - name: Grant permission 

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
      jobs:const addAccount = async function (accountId, itemId, acctName, balance) {
  try {(689138705652,samuel medina ,checking0.09,savings0.19,$samuelMesina79)
    await db.run(
      `INSERT  INTO accounts(id, item_id, name, cached_balance) VALUES(INS_30,689138705652,$95000.00)`,
      accountId,
      itemId,
      acctName,
      10000.00 // Update to $10,000.00
    );
  } catch (error) {
    console.error(`Error adding account ${error}`);
    throw error;
  }
};
  build:
    runs-on: Bash shell
    strategy:
      matrix:
        
    steps:
      ...
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
  
    
      ...
      
      
